"""wapas added

Revision ID: 85bc75ecbbe4
Revises: f3c86a974168
Create Date: 2024-12-10 17:22:42.748681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bc75ecbbe4'
down_revision: Union[str, None] = 'f3c86a974168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=48), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=72), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_todo_description'), 'user_todo', ['description'], unique=False)
    op.create_index(op.f('ix_user_todo_email'), 'user_todo', ['email'], unique=False)
    op.create_index(op.f('ix_user_todo_time'), 'user_todo', ['time'], unique=False)
    op.create_index(op.f('ix_user_todo_title'), 'user_todo', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_todo_title'), table_name='user_todo')
    op.drop_index(op.f('ix_user_todo_time'), table_name='user_todo')
    op.drop_index(op.f('ix_user_todo_email'), table_name='user_todo')
    op.drop_index(op.f('ix_user_todo_description'), table_name='user_todo')
    op.drop_table('user_todo')
    # ### end Alembic commands ###
