"""Initial commit

Revision ID: a57267922955
Revises: 85bc75ecbbe4
Create Date: 2024-12-17 14:39:00.362064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a57267922955'
down_revision: Union[str, None] = '85bc75ecbbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('User',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=72), nullable=True),
    # sa.Column('hashed_password', sa.String(length=72), nullable=True),
    # sa.Column('is_active', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    # op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    # op.drop_index('ix_User_id', table_name='user')
    # op.drop_index('ix_User_username', table_name='user')
    # op.drop_table('user')
    op.add_column('user_todo', sa.Column('user_id', sa.Integer(), nullable=True))
    # op.alter_column('user_todo', 'time',
    #            existing_type=mysql.DATETIME(),
    #            nullable=True)
    # op.drop_index('ix_user_todo_description', table_name='user_todo')
    # op.drop_index('ix_user_todo_email', table_name='user_todo')
    # op.drop_index('ix_user_todo_time', table_name='user_todo')
    # op.drop_index('ix_user_todo_title', table_name='user_todo')
    op.create_foreign_key(None, 'user_todo', 'User', ['user_id'], ['id'])
    # op.drop_column('user_todo', 'title')
    # op.drop_column('user_todo', 'is_sent')
    # op.drop_column('user_todo', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_todo', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user_todo', sa.Column('is_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user_todo', sa.Column('title', mysql.VARCHAR(length=48), nullable=True))
    #op.drop_constraint(None, 'user_todo', type_='foreignkey')
    op.create_index('ix_user_todo_title', 'user_todo', ['title'], unique=False)
    op.create_index('ix_user_todo_time', 'user_todo', ['time'], unique=False)
    op.create_index('ix_user_todo_email', 'user_todo', ['email'], unique=False)
    op.create_index('ix_user_todo_description', 'user_todo', ['description'], unique=False)
    op.alter_column('user_todo', 'time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    #op.drop_column('user_todo', 'user_id')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=72), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=72), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_User_username', 'user', ['username'], unique=True)
    op.create_index('ix_User_id', 'user', ['id'], unique=False)
    op.drop_index(op.f('ix_User_username'), table_name='User')
    #op.drop_index(op.f('ix_User_id'), table_name='User')
    #op.drop_table('User')
    # ### end Alembic commands ###
