"""added is_sent column in usertodo

Revision ID: f3c86a974168
Revises: c2eda45fccf0
Create Date: 2024-12-10 17:20:56.297070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3c86a974168'
down_revision: Union[str, None] = 'c2eda45fccf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_todo_description', table_name='user_todo')
    op.drop_index('ix_user_todo_email', table_name='user_todo')
    op.drop_index('ix_user_todo_time', table_name='user_todo')
    op.drop_index('ix_user_todo_title', table_name='user_todo')
    op.drop_table('user_todo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_todo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=72), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_todo_title', 'user_todo', ['title'], unique=False)
    op.create_index('ix_user_todo_time', 'user_todo', ['time'], unique=False)
    op.create_index('ix_user_todo_email', 'user_todo', ['email'], unique=False)
    op.create_index('ix_user_todo_description', 'user_todo', ['description'], unique=False)
    # ### end Alembic commands ###
